### ISSUE TITLE
How do I set environment variables for my services?

### ISSUE THREAD

**Issue by idcmardelplata** [rosineygp/mkdkr#150]
Hi I'm working on a basic Elixir/Phoenix project and I need to use a postgresql database, for this I usually build a container like this (as a service): 
`docker run -p 5432: 5432 -d -e POSTGRES_PASSWORD=postgres - e POSTGRES_USER=postgres -e POSTGRES_DB=justdrawcats -v pgdata: /var/lib/postgresql/data postgres`

but I wouldn't know how to do the same with mkdkr. Please, if you could guide me a bit, I would appreciate it, I have tried to do something like that but it doesn't work:

```Makefile
include $(shell [ ! -f .mkdkr ] && curl -fsSL https://git.io/JOBYz > .mkdkr; bash .mkdkr init)

server:
	@$(dkr)
	instance: elixir
	service: postgres
	#export POSTGRES_PASSWORD=postgres
	#export POSTGRES_USER=postgres
	#export POSTGRES_DB=test
	run: mix local.hex --force
	run: iex -S mix phx.server
```

**Comment by rosineygp** [comment]
you can attach de variables at Makefile,

```Makefile
include $(shell [ ! -f .mkdkr ] && curl -fsSL https://git.io/JOBYz > .mkdkr; bash .mkdkr init)

POSTGRES_PASSWORD=postgres
POSTGRES_USER=postgres
POSTGRES_DB=test

server:
	@$(dkr)
	service: postgres \
		-e POSTGRES_PASSWORD \
		-e POSTGRES_USER \
		-e POSTGRES_DB
	instance: elixir \
		-e POSTGRES_PASSWORD \
		-e POSTGRES_USER \
		-e POSTGRES_DB
	run: mix local.hex --force
	run: iex -S mix phx.server
```

or create all vars in shell


```shell
export POSTGRES_PASSWORD=postgres
export POSTGRES_USER=postgres
export POSTGRES_DB=test
```

```Makefile
include $(shell [ ! -f .mkdkr ] && curl -fsSL https://git.io/JOBYz > .mkdkr; bash .mkdkr init)

server:
	@$(dkr)
	service: postgres \
		-e POSTGRES_PASSWORD \
		-e POSTGRES_USER \
		-e POSTGRES_DB
	instance: elixir \
		-e POSTGRES_PASSWORD \
		-e POSTGRES_USER \
		-e POSTGRES_DB
	run: mix local.hex --force
	run: iex -S mix phx.server
```
	
service and instance are different containers... both needs the parameters

**Comment by idcmardelplata** [comment]
Thanks for response has helped me a lot. In gratitude I have made a video about mkdkr on youtube (for the latinoamerican community) you can see here if your like https://www.youtube.com/watch?v=DwDNqefP0v0
